#' checkPiamTemplates
#'
#' Checks if a given list of reported REMIND variables contains all the variables
#' expected in the piamInterfaces package.
#'
#' @param computedVariables list of reported REMIND variables
#' @param source of the reported variables (could be a gdx or folder path),
#' only used for generating a warning message
#' @export
checkPiamTemplates <- function(computedVariables, source) {

  # if you add a new template here, make sure to adjust the piamInterfaces version in the DESCRIPTION
  projects <- c("AR6", "AR6_NGFS", "ELEVATE", "NAVIGATE", "SHAPE", "ARIADNE", "ECEMF", "ScenarioMIP")

  templates <- NULL
  for (project in projects) {
    templates <- rbind(
      templates, data.frame(
        project = project,
        modelvars = piamInterfaces::getREMINDTemplateVariables(project)
      )
    )
  }

  templateVariables <- sort(unique(as.character(templates$modelvars))) %>%
  deletePlus() %>%
    unique()

  if (!any(computedVariables %in% templateVariables)) {
    stop("Something went wrong in 'checkPiamTemplates'. None of the variables are part of any template.")
  }

  missingVariables <- setdiff(templateVariables, computedVariables)

  if (length(missingVariables) > 0) {
    warning("The following variables are expected in the piamInterfaces package ",
            "for templates ", paste(projects, collapse = ", "),
            ",\nbut cannot be found in the reporting generated by ", source, ":\n ",
            paste(missingVariables, collapse = ",\n "),
            "\nTo find out where this variable is used, run: piamInterfaces::variableInfo('",
            magclass::unitsplit(missingVariables[[1]])$variable, "')",
            "\nPossible reasons are:\n",
            "- A variable was renamed in piamInterfaces, but not yet in the reporting, or inversely.\n",
            "  To rename in piamInterfaces, see https://github.com/pik-piam/piamInterfaces/blob/master/tutorial.md#renaming-a-piam_variable\n",
            "- A variable was removed from remind2. Then, it needs to be replaced or removed from piamInterfaces as well.\n",
            "- A variable is marked mandatory in piamInterfaces, while it is only reported for special REMIND settings/realizations.\n",
            "  Add an 'x' to the 'source' column in the mappings.")
  }

  missingVariables <- templates %>% filter(.data$modelvars %in% missingVariables)

  return(missingVariables)
}
